### ISSUE TITLE
question about multi-source fusion

### ISSUE THREAD

**Issue by Pixie8888** [Xiaoqi-Zhao-DLUT/Multi-Source-APS-ZVOS#1]
Hi,
Can I know rgb feature map F_rgb^i is which layer's output?
![image](https://user-images.githubusercontent.com/72333326/130173451-576ae9a6-32ce-4b9c-81cd-07ec5ec585f9.png)

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@Pixie412 
i ∈{1,2,3,4,5}, we just uses i to represent any layer. In the second stage, each layer's feature maps of each source will participate in the ISAM and FPM, and then we performs progressive fusion  for decoding.
![Screenshot from 2021-08-20 11-28-08](https://user-images.githubusercontent.com/25542131/130175137-40079adc-cb20-4b88-80ef-c4c2f4f0fcb3.png)
