### ISSUE TITLE
Some questions about the training method for stage 3

### ISSUE THREAD

**Issue by zp19990818** [Xiaoqi-Zhao-DLUT/Multi-Source-APS-ZVOS#2]
Hi~, Your work is really inspiring! But I still have some questions about stage 3.

As mentioned in the paper, stage 3 is a binary classification network, which is used to automatically select the prediction results. But I don't understand why to train a learnable classification network instead of choosing the final prediction result only by calculating the MAE of SOS, and MOS with GT directly. Because the prediction results of SOS and MOS have been obtained earlier. 

Looking forward to your reply🌹

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@zp19990818 There is no GT during inference.

**Comment by zp19990818** [comment]
> 

Got it! But what does "0.5" in inference.py mean? Does the output of stage 3 mean confidence in Mos?

![image](https://user-images.githubusercontent.com/53686038/233816849-868035d4-cdde-490c-82c8-d99d8096ffdc.png)
